### ISSUE TITLE
Information window uses Java icon

### ISSUE THREAD

**Issue by OlsonDev** [unsound/hfsexplorer#3]
It should use the application's icon instead of the default (ugly in my opinion) Java icon.

**Comment by OlsonDev** [comment]
So does `Memory statistics` & `Debug Console`.

**Comment by unsound** [comment]
Please check if this is fixed in fc191eb82a933b77843a60493a5b5744a4b0ae48.

**Comment by OlsonDev** [comment]
I do not have a Java environment set up to compile that but reading through the code, it looks to cover all instances I mentioned. I'd recommend creating a utility function to DRY out your code a little but that's your call.

**Comment by unsound** [comment]
You are really picky aren't you? ;-) If you would go through the rest of my code like that you'll find many other strange design decisions and various cases of code reptitiveness.
Anyway, just because you pointed it out I did clean this up by putting the repetitive code in a common superclass. See: 6a68a2d32149449f0a62742fdd01a40b284b8b1e

**Comment by OlsonDev** [comment]
Yup; I may be picky but have you seen Linus Torvalds? :-P Like I said, your call. I just appreciate clean code so I pointed it out. I approve of the changes! ;-)

Speaking of appreciation, thanks for making HFSExplorer, it's been pretty useful the past week or so.

**Comment by unsound** [comment]
If you're submitting code for the Linux kernel there's a whole other magnitude of stuff that can go wrong and affect everyone depending on Linux. I can fully sympathize with being extremely picky under those circumstances. :-)

Anyway, closing this issue now.
