### ISSUE TITLE
[Windows] Any possibility of not requiring Admin rights to use?

### ISSUE THREAD

**Issue by teknowledgist** [unsound/hfsexplorer#42]
I realize this is accessing hardware at a very low level, but the (completely correct) push to prevent users from having admin rights makes giving them quite problematic.  A lot of cyber-security insurance policies require highly restricted local Administrator groups to get reasonable rates.  

Do Linux users have to use `sudo` to use this software?

Thanks.

**Comment by unsound** [comment]
The application itself can be launched without admin rights but that means it's limited to opening disk images and possibly some external media but in general even those are restricted to admin/sudo privileges only. To access devices it needs admin/sudo privileges. This applies to all known operating systems... Linux, BSD, Solaris/OpenIndiana, Windows.

So the the application would always need admin/sudo rights at some level, but to reduce the attack surface it could be separated in a UI component and a daemon component, but that would required a complete rewrite separating the process accessing the disk from the UI. It's unlikely to happen any time soon and AFAIK there aren't any standard Java interfaces to fork off a privileged process, it would need special code in all supported operating systems. A major task.

I don't dispute that this is a more secure approach, on the other hand this software is (mostly) written in Java which is a memory safe language and it is used to access devices attached to your system, so we would need admin privileges at some level anyway. I.e. it wouldn't drop the requirement for elevating the daemon process (e.g. a UAC prompt).

**Comment by unsound** [comment]
Separating the application into a privileged service that's available on-demand and started by the system, and a GUI client for that service would require some serious thinking when designing the interface between the service and the client. Imagine that we have a privileged service that can open any device at the request of an unprivileged caller. A badly designed solution could enable an attacker to read otherwise restricted information from e.g. the NTFS root volume by opening its raw device through the service interface. In real-life use cases this could be less secure than a monolithic privileged app opened on demand and authorized by the user when needed.

**Comment by teknowledgist** [comment]
True.  Well, thanks for talking it through.  If a miracle occurs and you are inspired with a solution that would be great, but otherwise, I guess it's just our "cost" of accessing archival resources.

**Comment by unsound** [comment]
So I think I'll close this because I don't think there's any obvious solution for this issue that is adequate security-wise given the restrictions that all major operating systems enforce with regard to accessing block devices. If someone has a better idea, then please post a comment and reopen.
